
USE bd_ycourses;
/*INSERTANDO (34) COLUMNA(S)*/
INSERT INTO ciudad (idciudad,nombre,region)
VALUES 
(01,'Arica','Región de Arica y Parinacota'),
(02,'Gran Iquique','Región de Tarapacá'),
(03,'Pozo Almonte','Región de Tarapacá'),
(04,'Antofagasta','Región de Antofagasta'),
(05,'Calama','Región de Antofagasta'),
(06,'Tocopilla','Región de Antofagasta'),
(07,'Mejillones','Región de Antofagasta'),
(08,'La serena','Región de Coquimbo'),
(09,'Coquimbo','Región de Coquimbo'),
(10,'Ovalle','Región de Coquimbo'),
(11,'Combarbalá','Región de Coquimbo'),
(12,'Los Andes','Región de Valparíso'),
(13,'Valparaíso','Región de Valparíso'),
(14,'Viña del mar','Región de Valparíso'),
(15,'Santiago','Región Metropolitana'),
(16,'Rancagua','Region del Libertador Bernardo OHiggins'),
(17,'San Fernando','Region del Libertador Bernardo OHiggins'),
(18,'Talca','Región del Maule'),
(19,'Concepción','Región de Biobío'),
(20,'Talcahuano','Región del Maule'),
(21,'Chillán','Región de Ñuble'),
(22,'Temuco','Región de la Araucanía'),
(23,'Padre Las Casas','Región de la Araucanía'),
(24,'Angol','Región de la Araucanía'),
(25,'Lautaro','Región de la Araucanía'),
(26,'Valdivia','Región de Ríos'),
(27,'Los Lagos','Región de Ríos'),
(28,'Puerto Montt','Región de Los Lagos'),
(29,'Puerto Varas','Región de Los Lagos'),
(30,'Osorno','Región de Los Lagos'),
(31,'Coyhaique','Región de Aysén del General Carlos Ibanez del Campo'),
(32,'Puerto Aysén','Región de Aysén del General Carlos Ibanez del Campo'),
(33,'Punta Arenas','Región de Magallanes y la Antártica Chilena'),
(34,'Puerto Natales','Región de Magallanes y la Antártica Chilena');